# 1. SPRING CLOUD FUNCTION
spring.cloud.function.definition=${SPRING_CLOUD_FUNCTION_DEFINITION}

# 2. CONFIGURACOES DE EMAIL (AWS SES)
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 3. CONFIGURACOES AWS E DYNAMODB
# Usando REGION_NAME conforme configurado no seu GitHub Variables
aws.region=${REGION_NAME}
aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:}

# 4. LOGS
logging.level.com.luizalebs.notification_service=INFO