# 1. SPRING CLOUD FUNCTION
spring.cloud.function.definition=notificationFunction

# 2. CONFIGURACOES DE EMAIL
# O Spring vai buscar as variaveis que definimos no CloudFormation
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 3. CONFIGURACOES AWS E DYNAMODB
# Usando REGION_NAME para evitar conflito com variavel reservada da AWS
aws.region=${REGION_NAME}
aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:}

# 4. LOGS
logging.level.com.luizalebs.notification_service=INFO