# SPRING CLOUD FUNCTION
spring.cloud.function.definition=${SPRING_CLOUD_FUNCTION_DEFINITION}

# EMAIL CONFIG
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AWS AND DYNAMODB
aws.region=${REGION_NAME}
aws.dynamodb.endpoint=${AWS_DYNAMODB_ENDPOINT:}
table.name=${TABLE_NAME}

# LOGS
logging.level.com.luizalebs.notification_service=INFO