AWSTemplateFormatVersion: '2010-09-09'
Description: Tabela DynamoDB para Logs de Notificacao - Projeto Notification Service

Parameters:
  ProjectName:
    Type: String

  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod

Resources:
  NotificationLogsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${ProjectName}-${Environment}-logs"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

Outputs:
  TableName:
    Value: !Ref NotificationLogsTable
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DynamoTable"

  TableArn:
    Value: !GetAtt NotificationLogsTable.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-DynamoTableArn"