AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda do Microservico de Notificacao - Java Spring Cloud Function

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  LambdaMemory:
    Type: Number
    Default: 512
  LambdaTimeout:
    Type: Number
    Default: 30  # Essencial para o Cold Start do Spring
  ArtifactBucket:
    Type: String
  ArtifactKey:
    Type: String

Resources:
  NotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-handler"
      Runtime: java17 
      # ALINHAMENTO BACKEND: Handler padrao para Spring Cloud Function
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
      MemorySize: !Ref LambdaMemory
      Timeout: !Ref LambdaTimeout
      Role: 
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleArn"
      Code:
        S3Bucket: !Ref ArtifactBucket 
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          # ALINHAMENTO BACKEND: Nome do @Bean no seu LambdaConfig.java
          SPRING_CLOUD_FUNCTION_DEFINITION: notificationFunction
          TABLE_NAME: 
            Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DynamoTable"
      Tags:
        - Key: project
          Value: !Ref ProjectName
        - Key: environment
          Value: !Ref Environment

  LambdaServicePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ProjectName}-${Environment}-service-policy"
      Roles:
        - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleName"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # Permissao para Logs no DynamoDB
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
            Resource: 
              - Fn::ImportValue: !Sub "${ProjectName}-${Environment}-DynamoTableArn"
          # ALINHAMENTO BACKEND: Permissao para envio de E-mail via SES
          - Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: "*" 

Outputs:
  LambdaArn:
    Description: ARN da Lambda de Notificacao
    Value: !GetAtt NotificationLambda.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-LambdaArn"