AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda e API Gateway para o Notification Service

Parameters:
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  LambdaMemory:
    Type: Number
    Default: 512
  LambdaTimeout:
    Type: Number
    Default: 30
  ArtifactBucket:
    Type: String
  ArtifactKey:
    Type: String

Resources:
  # 1. A Função Lambda
  NotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-handler"
      Runtime: java17 
      Handler: org.anasantana.handler.NotificationHandler::handleRequest
      MemorySize: !Ref LambdaMemory
      Timeout: !Ref LambdaTimeout
      Role: 
        Fn::ImportValue: !Sub "${ProjectName}-${Environment}-LambdaExecutionRoleArn"
      Code:
        S3Bucket: !Ref ArtifactBucket 
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  # 2. O API Gateway (Necessário para o DNS funcionar)
  NotificationApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-api"

  # 3. O Domínio Personalizado no API Gateway
  ApiCustomDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      RegionalCertificateArn: !ImportValue 
        Fn::Sub: "${ProjectName}-${Environment}-CertificateArn"
      DomainName: api.asantanadev.com
      EndpointConfiguration:
        Types:
          - REGIONAL

Outputs:
  # ESSENCIAIS PARA O SEU ARQUIVO DNS.YAML FUNCIONAR:
  ApiGatewayDomainName:
    Value: !GetAtt ApiCustomDomain.RegionalDomainName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ApiGatewayDomainName"

  ApiGatewayHostedZoneId:
    Value: !GetAtt ApiCustomDomain.RegionalHostedZoneId
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ApiGatewayHostedZoneId"

  LambdaArn:
    Value: !GetAtt NotificationLambda.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-LambdaArn"